version: '3.1'
services:
  memcached:
    container_name: timemanager_app_memcached_main_container
    image: 'memcached:alpine'
    ports:
      - '7101:11211'

  redis:
    container_name: timemanager_app_redis_main_container
    image: 'redis:alpine'
    ports:
      - '7102:6379'

  postgres:
    container_name: timemanager_app_postgres_main_container
    image: 'postgres:16-alpine'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=timemanager_app
    ports:
      - '7103:5432'
